import pandas as pd
# data={"Calories":[420,310,500],"duration":[50,20,500]}
# df=pd.DataFrame(data)
# print(df)
# print("============================================================")
# print(df.loc[0])
# print("============================================================")
# df1=pd.DataFrame(data,index=["day1","day2","day3"])
# print(df1)
# print("============================================================")
# print(df1.loc["day2"])
df=pd.read_csv('D:\\OUTSIDE_STUFF\\PANDAS\\week_1.csv')
# print(df)
# print("==========================================================================")
# print(df.to_string())
# print(pd.options.display.max_rows)
print(df.head())
print(df.tail())
print(df.info())